
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: joinpod
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: joinpod-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: joinpod
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
  name: join-pod
  namespace: default
spec:
  serviceAccountName: joinpod
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["tail"]
    args: ["-f", "/dev/null"]
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      runAsNonRoot: false
  restartPolicy: Always
