apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: capi1-rke2
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.45.0.0/16
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.46.0.0/16
  topology:
    class: rke2-class
    controlPlane:
      metadata: {}
      replicas: 1
    variables:
    - name: dockerKindImage
      value: kindest/node:v1.34.0
    version: 1.34.0+rke2r1
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: 1
